fixtures:
  repositories:
    concat:      'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    dns: "#{source_dir}"
